# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cswclientdialogbase.ui'
#
# Created: Sat Oct 16 19:15:16 2010
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CSWClientDialog(object):
    def setupUi(self, CSWClientDialog):
        CSWClientDialog.setObjectName("CSWClientDialog")
        CSWClientDialog.resize(463, 638)
        self.verticalLayout = QtGui.QVBoxLayout(CSWClientDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(CSWClientDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabServers = QtGui.QWidget()
        self.tabServers.setObjectName("tabServers")
        self.gridLayout = QtGui.QGridLayout(self.tabServers)
        self.gridLayout.setObjectName("gridLayout")
        self.cmbConnections = QtGui.QComboBox(self.tabServers)
        self.cmbConnections.setObjectName("cmbConnections")
        self.gridLayout.addWidget(self.cmbConnections, 0, 0, 1, 5)
        self.btnServerInfo = QtGui.QPushButton(self.tabServers)
        self.btnServerInfo.setObjectName("btnServerInfo")
        self.gridLayout.addWidget(self.btnServerInfo, 1, 0, 1, 1)
        self.btnCapabilities = QtGui.QPushButton(self.tabServers)
        self.btnCapabilities.setObjectName("btnCapabilities")
        self.gridLayout.addWidget(self.btnCapabilities, 1, 1, 1, 2)
        self.btnNew = QtGui.QPushButton(self.tabServers)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout.addWidget(self.btnNew, 2, 0, 1, 1)
        self.btnEdit = QtGui.QPushButton(self.tabServers)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 2, 1, 1, 1)
        self.btnDelete = QtGui.QPushButton(self.tabServers)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 2, 2, 1, 1)
        self.btnSave = QtGui.QPushButton(self.tabServers)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 2, 4, 1, 1)
        self.textMetadata = QtGui.QTextEdit(self.tabServers)
        self.textMetadata.setObjectName("textMetadata")
        self.gridLayout.addWidget(self.textMetadata, 3, 0, 1, 5)
        self.btnAddDefault = QtGui.QPushButton(self.tabServers)
        self.btnAddDefault.setObjectName("btnAddDefault")
        self.gridLayout.addWidget(self.btnAddDefault, 1, 3, 1, 2)
        self.btnLoad = QtGui.QPushButton(self.tabServers)
        self.btnLoad.setObjectName("btnLoad")
        self.gridLayout.addWidget(self.btnLoad, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabServers, "")
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName("tabSearch")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabSearch)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.tabSearch)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leKeywords = QtGui.QLineEdit(self.tabSearch)
        self.leKeywords.setObjectName("leKeywords")
        self.horizontalLayout.addWidget(self.leKeywords)
        self.label_2 = QtGui.QLabel(self.tabSearch)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spnRecords = QtGui.QSpinBox(self.tabSearch)
        self.spnRecords.setObjectName("spnRecords")
        self.horizontalLayout.addWidget(self.spnRecords)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtGui.QGroupBox(self.tabSearch)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.leNorth = QtGui.QLineEdit(self.groupBox)
        self.leNorth.setObjectName("leNorth")
        self.gridLayout_4.addWidget(self.leNorth, 0, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.leWest = QtGui.QLineEdit(self.groupBox)
        self.leWest.setObjectName("leWest")
        self.gridLayout_4.addWidget(self.leWest, 1, 0, 1, 2)
        self.leEast = QtGui.QLineEdit(self.groupBox)
        self.leEast.setObjectName("leEast")
        self.gridLayout_4.addWidget(self.leEast, 1, 2, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.leSouth = QtGui.QLineEdit(self.groupBox)
        self.leSouth.setObjectName("leSouth")
        self.gridLayout_4.addWidget(self.leSouth, 2, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 2, 1)
        self.btnCanvasBbox = QtGui.QPushButton(self.groupBox)
        self.btnCanvasBbox.setObjectName("btnCanvasBbox")
        self.gridLayout_5.addWidget(self.btnCanvasBbox, 0, 1, 1, 1)
        self.btnGlobalBbox = QtGui.QPushButton(self.groupBox)
        self.btnGlobalBbox.setObjectName("btnGlobalBbox")
        self.gridLayout_5.addWidget(self.btnGlobalBbox, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.btnSearch = QtGui.QPushButton(self.tabSearch)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout_2.addWidget(self.btnSearch)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblResults = QtGui.QLabel(self.tabSearch)
        self.lblResults.setObjectName("lblResults")
        self.gridLayout_2.addWidget(self.lblResults, 0, 0, 1, 4)
        self.treeRecords = QtGui.QTreeWidget(self.tabSearch)
        self.treeRecords.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeRecords.setAlternatingRowColors(True)
        self.treeRecords.setRootIsDecorated(False)
        self.treeRecords.setItemsExpandable(False)
        self.treeRecords.setAllColumnsShowFocus(True)
        self.treeRecords.setObjectName("treeRecords")
        self.treeRecords.header().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.treeRecords, 1, 0, 1, 4)
        self.btnFirst = QtGui.QPushButton(self.tabSearch)
        self.btnFirst.setObjectName("btnFirst")
        self.gridLayout_2.addWidget(self.btnFirst, 2, 0, 1, 1)
        self.btnPrev = QtGui.QPushButton(self.tabSearch)
        self.btnPrev.setObjectName("btnPrev")
        self.gridLayout_2.addWidget(self.btnPrev, 2, 1, 1, 1)
        self.btnNext = QtGui.QPushButton(self.tabSearch)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout_2.addWidget(self.btnNext, 2, 2, 1, 1)
        self.btnLast = QtGui.QPushButton(self.tabSearch)
        self.btnLast.setObjectName("btnLast")
        self.gridLayout_2.addWidget(self.btnLast, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtGui.QLabel(self.tabSearch)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 4)
        self.textAbstract = QtGui.QTextEdit(self.tabSearch)
        self.textAbstract.setObjectName("textAbstract")
        self.gridLayout_3.addWidget(self.textAbstract, 1, 0, 1, 4)
        self.leDataUrl = QtGui.QLineEdit(self.tabSearch)
        self.leDataUrl.setObjectName("leDataUrl")
        self.gridLayout_3.addWidget(self.leDataUrl, 2, 0, 1, 4)
        self.btnAddToWms = QtGui.QPushButton(self.tabSearch)
        self.btnAddToWms.setObjectName("btnAddToWms")
        self.gridLayout_3.addWidget(self.btnAddToWms, 3, 0, 1, 1)
        self.btnOpenUrl = QtGui.QPushButton(self.tabSearch)
        self.btnOpenUrl.setObjectName("btnOpenUrl")
        self.gridLayout_3.addWidget(self.btnOpenUrl, 3, 1, 1, 1)
        self.btnMetadata = QtGui.QPushButton(self.tabSearch)
        self.btnMetadata.setObjectName("btnMetadata")
        self.gridLayout_3.addWidget(self.btnMetadata, 3, 2, 1, 1)
        self.btnShowXml = QtGui.QPushButton(self.tabSearch)
        self.btnShowXml.setObjectName("btnShowXml")
        self.gridLayout_3.addWidget(self.btnShowXml, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tabSearch, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(CSWClientDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CSWClientDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CSWClientDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CSWClientDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CSWClientDialog)

    def retranslateUi(self, CSWClientDialog):
        CSWClientDialog.setWindowTitle(QtGui.QApplication.translate("CSWClientDialog", "CSW client", None, QtGui.QApplication.UnicodeUTF8))
        self.btnServerInfo.setText(QtGui.QApplication.translate("CSWClientDialog", "Server info", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCapabilities.setText(QtGui.QApplication.translate("CSWClientDialog", "GetCapabilities response", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("CSWClientDialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setText(QtGui.QApplication.translate("CSWClientDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("CSWClientDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("CSWClientDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDefault.setText(QtGui.QApplication.translate("CSWClientDialog", "Add default servers", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("CSWClientDialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServers), QtGui.QApplication.translate("CSWClientDialog", "Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CSWClientDialog", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CSWClientDialog", "Return records", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CSWClientDialog", "Bounding box", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCanvasBbox.setText(QtGui.QApplication.translate("CSWClientDialog", "From map canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGlobalBbox.setText(QtGui.QApplication.translate("CSWClientDialog", "Set global", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("CSWClientDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.setSortingEnabled(True)
        self.treeRecords.headerItem().setText(0, QtGui.QApplication.translate("CSWClientDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.headerItem().setText(1, QtGui.QApplication.translate("CSWClientDialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.headerItem().setText(2, QtGui.QApplication.translate("CSWClientDialog", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFirst.setText(QtGui.QApplication.translate("CSWClientDialog", "First", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrev.setText(QtGui.QApplication.translate("CSWClientDialog", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setText(QtGui.QApplication.translate("CSWClientDialog", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLast.setText(QtGui.QApplication.translate("CSWClientDialog", "Last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CSWClientDialog", "Abstract", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddToWms.setText(QtGui.QApplication.translate("CSWClientDialog", "Add to WMS list", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpenUrl.setText(QtGui.QApplication.translate("CSWClientDialog", "Open URL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMetadata.setText(QtGui.QApplication.translate("CSWClientDialog", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowXml.setText(QtGui.QApplication.translate("CSWClientDialog", "View XML", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("CSWClientDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))

